extends:
  - plugin:@lichtblick/base
  - plugin:@lichtblick/jest

env:
  browser: true
  es6: true
  node: true

ignorePatterns:
  - dist

rules:
  no-restricted-syntax:
    - error
    - selector: 'BinaryExpression[operator=">>"]'
      message: When working with unsigned numbers, use the unsigned right shift operator `>>>`.

overrides:
  - files: ["*.ts", "*.tsx"]
    extends:
      - plugin:@lichtblick/typescript
    parserOptions:
      project: tsconfig.eslint.json
